# Generated by Django 6.0.5 on 2026-06-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('wind_speed', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('pressure', models.FloatField()),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
